### ISSUE TITLE
Permission denied when executing ./setup.sh and Make All

### ISSUE THREAD

**Issue by 3dgoose** [lowlevellearning/rosetta-stone#5]
`bash: ./setup.sh: Permission denied`
`powerpc-linux-gnu-gcc -o ppc rosetta.c -static
make: powerpc-linux-gnu-gcc: Command not found
make: *** [Makefile:6: powerpc] Error 127`

**Comment by danielhejduk** [comment]
try `chmod +x setup.sh` and after that execute the script

**Comment by 3dgoose** [comment]
Yea.. Im feeling bad now
